Repository TokTok/toxic, pull requests merged in 2020-10, with the labels that each got.

#91 chore: Bump to version 0.8.4
  apidoc/python/source/conf.py
  cfg/global_vars.mk
Labels: chore, hacktoberfest-accepted, packaging

#92 fix: Incorrect file specified error when building in WSL from CLion
  Makefile
Labels: bug

#93 fix: Wformat-truncation warnings due to snprintf() misuse
  src/autocomplete.c
  src/chat.c
  src/friendlist.c
  src/group_commands.c
  src/name_lookup.c
Labels: bug

#96 cleanup: Reduce size of some large stack memory allocations
  src/autocomplete.c
  src/curl_util.h
  src/global_commands.c
  src/notify.c
  src/prompt.h
Labels: cleanup

#99 fix: regression related to https lookups
  src/bootstrap.c
  src/curl_util.h
  src/name_lookup.c
Labels: bug

#98 cleanup: Dynamically allocate audio frame buffer memory
  src/audio_call.c
  src/audio_call.h
  src/audio_device.c
Labels: bug, cleanup

#103 chore: Use c99 standard instead of gnu99
  Makefile
Labels: chore
