Repository TokTok/toxic, pull requests merged in 2020-05, with the labels that each got.

#81 chore: Remove astyle from travis build.
  .travis.yml
  cfg/checks/audio.mk
  cfg/checks/check_features.mk
  cfg/checks/desktop_notifications.mk
Labels: chore

#80 chore: Use global release-drafter config.
  .github/release-drafter.yml
  .github/settings.yml
Labels: chore

#76 chore: Add macOS build to Travis CI.
  .travis.yml
Labels: chore

#84 feat: Add the ability to log to file
  src/toxic.c
  src/windows.h
Labels: enhancement

#85 fix: Make sure logger file is closed after tox_kill
  src/toxic.c
Labels: bug

#86 fix: A couple small fixes
  src/friendlist.c
  src/toxic.c
Labels: bug
