Repository TokTok/toxic, pull requests merged in 2020-12, with the labels that each got.

#163 cleanup: Remove lots of duplicate code related to printing timestamps
  src/api.c
  src/audio_call.c
  src/audio_device.c
  src/autocomplete.c
  src/chat.c
  src/chat_commands.c
  src/conference.c
  src/conference_commands.c
  src/execute.c
  src/file_transfers.c
  src/friendlist.c
  src/global_commands.c
  src/line_info.c
  src/line_info.h
  src/log.c
  src/misc_tools.c
  src/misc_tools.h
  src/name_lookup.c
  src/prompt.c
  src/toxic.c
  src/video_call.c
  src/video_device.c
Labels: chore, cleanup

#164 fix: Don't announce when ghost peers leave the group
  src/conference.c
Labels: bug

#166 feat: Custom colors proof of concept
  misc/toxic.conf.example
  src/chat.c
  src/prompt.c
  src/settings.c
  src/settings.h
  src/toxic.c
  src/toxic.h
  src/windows.c
  src/windows.h
Labels: enhancement

#169 fix: off by one error and comment magic numbers
  src/line_info.c
Labels: bug, cleanup

#168 chore: Add config man entries for colour scheme options
  doc/toxic.conf.5
  doc/toxic.conf.5.asc
  misc/toxic.conf.example
Labels: chore
