Repository TokTok/toxic, pull requests merged in 2020-11, with the labels that each got.

#97 fix: invalid usage of stderr and incorrect formatting
  src/friendlist.c
  src/line_info.c
  src/toxic.c
Labels: bug

#106 cleanup: Fix a few issues
  src/avatars.c
  src/chat.c
  src/chat_commands.c
  src/friendlist.c
  src/line_info.c
  src/misc_tools.c
  src/term_mplex.c
  src/toxic.c
Labels: cleanup

#110 cleanup: fix bad behaviour with duplicate file names
  src/chat.c
Labels: cleanup

#109 cleanup: Replace deprecated usleep function with nanosleep
  src/audio_device.c
  src/misc_tools.c
  src/misc_tools.h
  src/notify.c
  src/toxic.c
  src/video_device.c
  src/xtra.c
Labels: chore, cleanup

#112 cleanup: Filter invalid file names for inbound file transfers
  src/chat.c
Labels: cleanup

#114 cleanup: Fix char -> widechar comparisons
  src/chat.c
  src/friendlist.c
  src/groupchat.c
  src/help.c
Labels: cleanup

#113 chore: Rename: groupchats -> conferences
  Makefile
  src/chat.c
  src/chat_commands.c
  src/chat_commands.h
  src/conference.c
  src/conference.h
  src/conference_commands.c
  src/conference_commands.h
  src/execute.c
  src/execute.h
  src/friendlist.c
  src/friendlist.h
  src/global_commands.c
  src/global_commands.h
  src/help.c
  src/help.h
  src/input.c
  src/line_info.c
  src/log.c
  src/log.h
  src/misc_tools.c
  src/misc_tools.h
  src/prompt.c
  src/python_api.c
  src/toxic.c
  src/toxic.h
  src/windows.c
  src/windows.h
Labels: chore, cleanup

#119 fix: Race condition
  src/chat.c
  src/conference.c
  src/notify.c
  src/notify.h
Labels: bug

#122 cleanup: Use compound literals to zero out structs instead of memset
  Makefile
  src/audio_call.c
  src/avatars.c
  src/chat.c
  src/conference.c
  src/file_transfers.c
  src/friendlist.c
  src/global_commands.c
  src/help.c
  src/log.c
  src/name_lookup.c
  src/notify.c
  src/prompt.c
  src/toxic.c
  src/video_device.c
Labels: cleanup

#123 cleanup: Refactor message queue
  src/message_queue.c
  src/message_queue.h
  src/toxic.c
Labels: cleanup, enhancement

#124 fix: bugs/issues with the message queue
  src/message_queue.c
Labels: bug, cleanup

#126 fix: some issues with file transfers
  src/avatars.c
  src/avatars.h
  src/chat.c
  src/chat_commands.c
  src/file_transfers.c
  src/file_transfers.h
  src/windows.c
Labels: bug, cleanup

#129 chore: Bump to version 0.9.0
  apidoc/python/source/conf.py
  cfg/global_vars.mk
Labels: chore, packaging

#130 fix: bug sometimes preventing typing status from being updated
  src/chat.c
Labels: bug

#133 fix: playing unallocated memory on opening audio device
  src/audio_device.c
Labels: bug

#134 feat: Refactor/improve logging
  src/chat.c
  src/conference.c
  src/conference.h
  src/conference_commands.c
  src/friendlist.c
  src/global_commands.c
  src/log.c
  src/log.h
  src/prompt.c
Labels: enhancement, refactor

#135 feat: Use two channels for conference audio
  src/conference.c
Labels: enhancement

#136 feat: Add config settings for audio channels
  doc/toxic.conf.5
  doc/toxic.conf.5.asc
  misc/toxic.conf.example
  src/audio_call.c
  src/conference.c
  src/settings.c
  src/settings.h
Labels: enhancement

#131 feat: Implement push-to-talk for conference audio
  doc/toxic.conf.5
  doc/toxic.conf.5.asc
  misc/toxic.conf.example
  src/conference.c
  src/conference.h
  src/conference_commands.c
  src/conference_commands.h
  src/execute.c
  src/help.c
  src/settings.c
  src/settings.h
Labels: enhancement

#141 feat: Some UI improvements
  src/friendlist.c
  src/misc_tools.c
  src/prompt.c
  src/toxic.c
  src/windows.c
  src/windows.h
Labels: enhancement

#139 cleanup: Some code cleanup and fixes
  src/api.c
  src/audio_call.c
  src/chat.c
  src/conference.c
  src/friendlist.c
  src/global_commands.c
  src/log.c
  src/python_api.c
  src/xtra.c
Labels: cleanup

#146 fix: UI regression
  src/misc_tools.c
Labels: bug

#150 feat: Add notification counters to bottom tab
  src/global_commands.c
  src/notify.c
  src/windows.c
  src/windows.h
Labels: enhancement

#153 fix: Properly handle failures to convert widechar strings to multibyte
  src/chat.c
  src/conference.c
  src/prompt.c
Labels: bug

#145 cleanup: cleanup and refactor x11 code
  cfg/checks/x11.mk
  src/notify.c
  src/toxic.c
  src/x11focus.c
  src/x11focus.h
  src/xtra.c
Labels: cleanup

#151 fix: some off by one bugs with line scrolling and some cleanup
  src/line_info.c
  src/line_info.h
  src/message_queue.c
Labels: bug, cleanup

#155 fix: small regression
  src/message_queue.c
Labels: bug

#143 chore: Add release and LLVM asan build options
  INSTALL.md
  Makefile
  cfg/targets/help.mk
Labels: chore

#154 fix: Another logging fix
  src/log.c
Labels: bug

#157 fix: tab complete bug
  src/autocomplete.c
Labels: bug

#158 chore: Update readme screenshot and bump to v0.9.1
  README.md
  apidoc/python/source/conf.py
  cfg/global_vars.mk
  doc/toxic.1
Labels: chore, packaging

#159 fix: a couple minor issues
  src/line_info.c
  src/log.c
Labels: bug, cleanup
