Repository TokTok/toxic, pull requests merged in 2021-12, with the labels that each got.

#195 chore: Use toktok-stack 0.0.23 for cirrus builds.
  .cirrus.yml
Labels: chore

#197 cleanup: do exact length check for string passed to tox_pk_string_to_bytes
  src/misc_tools.c
Labels: cleanup

#198 cleanup: Avoid casting away constness from pointers.
  src/autocomplete.c
  src/friendlist.c
  src/misc_tools.c
  src/video_device.c
  src/windows.c
Labels: cleanup

#199 cleanup: Reduce the amount of "extern" in .c files.
  src/api.c
  src/audio_call.c
  src/bootstrap.c
  src/chat.c
  src/conference.c
  src/friendlist.c
  src/friendlist.h
  src/global_commands.c
  src/name_lookup.c
  src/prompt.h
  src/settings.h
  src/toxic.c
  src/toxic.h
  src/video_device.c
  src/windows.c
  src/windows.h
Labels: cleanup

#200 chore: Add github CI workflow.
  .github/workflows/ci.yml
Labels: chore

#201 chore: Fix CI: don't install bootstrap daemon.
  .github/settings.yml
  .github/workflows/ci.yml
Labels: chore

#202 chore: Add "infer" static analysis action on CI.
  .github/settings.yml
  .github/workflows/ci.yml
Labels: chore

#203 chore: make infer print full log
  .github/workflows/ci.yml
Labels: chore

#204 cleanup: do proper error handling for a few malloc calls
  src/notify.c
  src/notify.h
  src/video_device.c
Labels: cleanup

#205 cleanup: fix some uninitialized memory warnings and clarify some logic
  src/game_base.c
  src/game_chess.c
  src/line_info.c
  src/name_lookup.c
  src/windows.c
Labels: cleanup

#206 cleanup: add missing ifdef
  src/toxic.c
Labels: cleanup

#207 cleanup: remove unnecessary define for keeping track of string array size
  src/execute.c
Labels: cleanup

#209 chore: Fix BUILD format (we check this on toktok-stack now).
  .cirrus.yml
  BUILD.bazel
Labels: chore

#208 feat: Implement file transfer queue for offline friends
  src/chat.c
  src/chat_commands.c
  src/file_transfers.c
  src/file_transfers.h
  src/friendlist.c
  src/friendlist.h
  src/windows.c
Labels: enhancement

#210 fix: send file control cancel when we block or delete a friend
  src/file_transfers.c
  src/friendlist.c
Labels: bug

#211 chore: bump version to 0.11.3 and update toxcore version in static build script
  .cirrus.yml
  apidoc/python/source/conf.py
  cfg/global_vars.mk
  script/build-minimal-static-toxic.sh
Labels: chore
