Repository TokTok/toxic, pull requests merged in 2021-01, with the labels that each got.

#172 Fix: minor display bug with the audio call info box
  src/chat.c
Labels: Fix, bug

#174 fix: bug sometimes causing join message spam on conference join
  src/conference.c
Labels: bug

#177 cleanup: Rename some build options for naming consistency
  Makefile
  cfg/targets/help.mk
Labels: cleanup

#178 fix: Makefile assignment bug
  Makefile
Labels: bug

#176 feat: add a script for building minimal static toxic
  script/build-minimal-static-toxic.sh
Labels: enhancement

#179 chore: Bump to version 0.10.1
  apidoc/python/source/conf.py
  cfg/global_vars.mk
Labels: chore, packaging

#180 fix: bug preventing the /clear command from working in Home window
  src/prompt.c
Labels: bug

#182 chore: Show previous window instead of Home after closing a window
  src/windows.c
Labels: Fix, chore

#183 fix: buggy behaviour when printing non-ascii characters in Home input field
  src/prompt.c
Labels: bug
