Repository TokTok/toxic, pull requests merged in 2022-01, with the labels that each got.

#212 fix: static build
  script/build-minimal-static-toxic.sh
Labels: bug, chore

#214 fix: make sure we check for duplicate paths in pending file transfers list
  src/chat.c
  src/file_transfers.c
  src/file_transfers.h
Labels: bug

#215 feat: add some simple impersonation detection on friend requests
  src/chat.c
  src/log.c
  src/prompt.c
  src/toxic.h
Labels: enhancement

#216 fix: use widechars to display strings in the UI
  src/line_info.c
  src/line_info.h
  src/toxic.h
Labels: bug

#218 chore: Use latest instead of versioned toktok-stack image.
  .cirrus.yml
  .github/settings.yml
Labels: chore
