Repository TokTok/toxic, pull requests merged in 2024-12, with the labels that each got.

#390 cleanup: Fix layering checks and mark toxic as no-windows.
  BUILD.bazel
Labels: cleanup

#388 feat: disable toxcore DNS lookups when proxy is set with UDP disabled
  astylerc
  script/build-minimal-static-toxic.sh
  src/main.c
Labels: enhancement

#391 feat: Add the ability to pass a password to the groupchat /rejoin command
  src/execute.c
  src/global_commands.c
  src/groupchat_commands.c
  src/groupchats.c
  src/groupchats.h
  src/help.c
Labels: enhancement

#387 feat: Allow friend invites from group and conference windows
  src/chat_commands.c
  src/chat_commands.h
  src/conference.c
  src/conference_commands.c
  src/conference_commands.h
  src/execute.c
  src/friendlist.c
  src/friendlist.h
  src/groupchat_commands.c
  src/groupchat_commands.h
  src/groupchats.c
  src/help.c
Labels: enhancement

#392 fix: help menu bugs
  src/groupchats.c
  src/help.c
Labels: bug

#395 cleanup: Stop using deprecated names for things in tox.h.
  src/groupchats.c
  src/groupchats.h
  src/main.c
  src/toxic.h
  src/windows.c
  src/windows.h
Labels: cleanup

#394 feat: Add word block list to config
  doc/toxic.conf.5
  doc/toxic.conf.5.asc
  misc/toxic.conf.example
  src/api.c
  src/audio_call.c
  src/audio_device.c
  src/chat.c
  src/conference.c
  src/groupchats.c
  src/main.c
  src/misc_tools.c
  src/misc_tools.h
  src/notify.c
  src/prompt.c
  src/python_api.c
  src/qr_code.c
  src/settings.c
  src/settings.h
  src/toxic.c
  src/toxic.h
  src/toxic_constants.h
  src/video_call.c
  src/windows.c
Labels: enhancement
