Repository TokTok/toxic, pull requests merged in 2024-03, with the labels that each got.

#366 refactor: Move message init queue to separate file
  Makefile
  src/init_queue.c
  src/init_queue.h
  src/main.c
  src/toxic.c
  src/toxic.h
Labels: refactor

#368 chore: update group private message API function
  src/toxic.h
  src/windows.c
Labels: api break, chore

#358 cleanup: fix static assert on MacOS
  src/toxic.h
Labels: cleanup

#370 chore: bump to version 0.15.0
  .cirrus.yml
  apidoc/python/source/conf.py
  cfg/global_vars.mk
  script/build-minimal-static-toxic.sh
Labels: chore

#371 chore: Update static binary with latest toxcore version
  script/build-minimal-static-toxic.sh
Labels: chore

#372 fix: syntax errors in config example file
  misc/toxic.conf.example
Labels: documentation

#373 chore: Update the static build script
  script/build-minimal-static-toxic.sh
Labels: chore

#375 fix: Static build on non-amd64 targets
  script/build-minimal-static-toxic.sh
Labels: chore

#374 chore: bump to version 0.15.1
  apidoc/python/source/conf.py
  cfg/global_vars.mk
Labels: chore
